'use strict';

const repo = require('./repo');

const AUTHORS = {
  arthur: {
    name: 'Arthur Wren',
    email: 'arthur.wren@fairfield-law.com'
  },
  eleanor: {
    name: 'Eleanor Wren',
    email: 'e.wren@alumna.stanford.edu'
  },
  margaret: {
    name: 'Margaret Chen-Wren',
    email: 'margaret.chen@meridianhealth.org'
  },
  david: {
    name: 'David Wren',
    email: 'davidwren@icloud.com'
  }
};

const BRANCHES = {
  review: 'eleanor-review',
  contested: 'contestation',
  private: 'private-drafts'
};

function makeWillDoc(sections) {
  return sections.join('\n\n');
}

const COMMIT_TIMELINE = [
  {
    date: '2024-01-08T10:30:00-05:00',
    author: 'arthur',
    message: 'Initial draft of last will and testament',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, being of sound mind and body, do hereby declare this to be my last will and testament, revoking all prior wills and codicils.',
      '',
      '## ARTICLE I: FAMILY',
      'I am married to Arthur Wren. We have two adult children: Margaret Chen-Wren and David Wren.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following:',
      '- My grandmother\'s wedding ring to my daughter, Margaret.',
      '- My collection of first editions to my son, David.',
      '- The lake house on Cedar Pond to be shared equally between my children for their lifetimes.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All remaining assets shall be divided equally among my husband and two children.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'As my children are adults, no guardian provisions are necessary.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I wish to be cremated. I wish for my ashes to be scattered at Cedar Pond, among the birch trees on the eastern shore, where the morning light comes through.',
      '',
      'Eleanor Wren',
      'Date: ___________'
    ])
  },
  {
    date: '2024-01-12T09:15:00-05:00',
    author: 'arthur',
    message: 'Add legal preamble, standard testamentary language',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (appraised value: $14,200) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-01-18T14:22:00-05:00',
    author: 'eleanor',
    message: 'Reviewing Arthur\'s draft. Added personal note. Some concerns about the legal tone.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items, given with love:',
      '- My grandmother\'s wedding ring to my daughter, Margaret. You know why it\'s yours.',
      '- My collection of first editions to my son, David. Take care of them, but more importantly, read them.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship. This was always meant to be yours.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light, where we used to go.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-01-19T08:45:00-05:00',
    author: 'arthur',
    message: 'Reverted personal additions. Maintained formal testamentary language only.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (appraised value: $14,200) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-01-25T16:10:00-05:00',
    author: 'eleanor',
    message: 'Created my review branch. Adding my annotations where Arthur won\'t remove them.',
    branch: BRANCHES.review,
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond.',
      '',
      '[NOTE FROM ELEANOR: Arthur, we need to discuss Helen. I\'m not sure about the successor executor choice. She lives in Oregon now and we barely speak. I\'d prefer Margaret. I know that creates complications with the bequests but she\'s the one who shows up.]',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (appraised value: $14,200) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '[NOTE FROM ELEANOR: The birch trees. You remember the birch trees.]',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-02-02T11:30:00-05:00',
    author: 'margaret',
    message: 'Mom asked me to look at the will. Initial review.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint Margaret Chen-Wren as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (appraised value: $14,200) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-02-03T01:17:00-05:00',
    author: 'arthur',
    message: 'Corrected executor provision. Reverted successor to original designation.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (appraised value: $14,200) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-02-10T19:45:00-05:00',
    author: 'margaret',
    message: 'Added trust provisions for lake house. Protecting Mom\'s intentions.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (appraised value: $14,200) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," shall be placed in an irrevocable trust for the benefit of my children, Margaret Chen-Wren and David Wren, in equal shares, for their lifetimes, with right of survivorship. The trustee shall be Margaret Chen-Wren. The property may not be sold, mortgaged, or encumbered without the written consent of both beneficiaries.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-02-11T06:03:00-05:00',
    author: 'arthur',
    message: 'Removed trust language. Lake house reverts to standard joint tenancy clause.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (appraised value: $14,200) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-02-14T22:08:00-05:00',
    author: 'david',
    message: 'first time looking at this. margaret sent me the file. i don\'t know what to say.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (appraised value: $14,200) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-02-20T15:33:00-05:00',
    author: 'arthur',
    message: 'Updated asset valuations per recent appraisal',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (current appraised value: $18,400) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes, appraised value: $52,000) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road (current assessed value: $385,000), referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-02-28T10:00:00-05:00',
    author: 'eleanor',
    message: 'I want to add a letter. Just for my children. Arthur can\'t edit this out.',
    branch: BRANCHES.private,
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (current appraised value: $18,400) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes, appraised value: $52,000) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road (current assessed value: $385,000), referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '## LETTER TO MY CHILDREN',
      'Margaret, David —',
      'If you are reading this, I am gone. I\'m sorry for that. I\'m sorry for a lot of things.',
      '',
      'I want you to know that this will does not contain everything I wish I could give you. Some things cannot be put in legal language. The way Margaret looked after me these last months, driving three hours each weekend, sitting through appointments no daughter should have to sit through — that is not something a bequest can honor. But I see you, sweetheart. I see everything you do.',
      '',
      'David — I know I have been distant. I know the phone calls went both ways and I was the one who stopped picking up. You deserved a mother who showed up. I was sick and I was scared and I convinced myself that you were better off without watching. I was wrong about that. I was wrong about so many things.',
      '',
      'Your father and I — things have not been good for a long time. You both know this. The will gives him everything because that is how these documents work, because that is what he will expect, because I do not have the fight left in me. But the lake house is yours. Hold onto it. Go to the birch trees. Remember what it was like before everything got complicated.',
      '',
      'I love you both. Past tense is not something I accept.',
      '',
      'Mom',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-03-05T03:42:00-05:00',
    author: 'david',
    message: 'i can\'t sleep. i keep reading this. margaret says arthur keeps changing things.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring (current appraised value: $18,400) to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes, appraised value: $52,000) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road (current assessed value: $385,000), referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-03-05T07:28:00-05:00',
    author: 'arthur',
    message: 'Family revisions, final cleanup before attorney review',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My personal book collection to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to my husband, Arthur Wren, to manage and maintain for the benefit of the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, in fee simple absolute.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my remains be handled at the discretion of my executor.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-03-05T14:55:00-05:00',
    author: 'margaret',
    message: 'WHAT DID YOU DO. You redirected the lake house to yourself. You removed the valuations. David showed me.',
    branch: BRANCHES.contested,
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship. This property may not be sold or transferred outside the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-03-06T02:14:00-05:00',
    author: 'david',
    message: 'i don\'t know if this is right but margaret says we need a record. arthur changed mom\'s will. the lake house was supposed to be ours. the ashes. he changed where her ashes go.',
    branch: BRANCHES.contested,
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be shared equally between my children for their lifetimes, with right of survivorship. This property may not be sold or transferred outside the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '## PERSONAL STATEMENT',
      'My mother wanted the birch trees. My mother wanted the lake house to belong to us. My mother wanted Margaret as successor executor. Arthur changed all of it while she was too sick to notice.',
      '',
      'I am not a lawyer. I am not even a very good son. But I know what my mother wanted, because she told me, the last time I visited, when she could still talk, and she said: David, promise me the birch trees.',
      '',
      'I promised.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-03-06T09:40:00-05:00',
    author: 'arthur',
    message: 'Restored attorney-approved version. Removed unauthorized additions.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My personal book collection to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to my husband, Arthur Wren, to manage and maintain for the benefit of the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, in fee simple absolute.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my remains be handled at the discretion of my executor.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-03-10T01:33:00-05:00',
    author: 'david',
    message: 'she\'s getting worse. i drove up tonight. the house is quiet. arthur is asleep and i\'m sitting with her and she can\'t talk anymore but she keeps reaching for my hand.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My personal book collection to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to my husband, Arthur Wren, to manage and maintain for the benefit of the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, in fee simple absolute.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my remains be handled at the discretion of my executor.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-03-15T11:20:00-05:00',
    author: 'arthur',
    message: 'Final version. Ready for execution and notarization.',
    branch: 'main',
    tag: 'final-draft',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My personal book collection to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to my husband, Arthur Wren, to manage and maintain for the benefit of the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, in fee simple absolute.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my remains be handled at the discretion of my executor.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-03-22T08:15:00-04:00',
    author: 'margaret',
    message: 'She\'s gone. March 19. I\'m copying the will as it exists. For the record.',
    branch: BRANCHES.contested,
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I was married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my daughter, Margaret Chen-Wren, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be placed in an irrevocable trust for the benefit of my children, Margaret Chen-Wren and David Wren, in equal shares, for their lifetimes. The property may not be sold or transferred outside the family. The trustee shall be Margaret Chen-Wren.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '## LETTER TO MY CHILDREN',
      'Margaret, David —',
      'If you are reading this, I am gone. I\'m sorry for that. I\'m sorry for a lot of things.',
      '',
      'I want you to know that this will does not contain everything I wish I could give you. Some things cannot be put in legal language. The way Margaret looked after me these last months, driving three hours each weekend, sitting through appointments no daughter should have to sit through — that is not something a bequest can honor. But I see you, sweetheart. I see everything you do.',
      '',
      'David — I know I have been distant. I know the phone calls went both ways and I was the one who stopped picking up. You deserved a mother who showed up. I was sick and I was scared and I convinced myself that you were better off without watching. I was wrong about that. I was wrong about so many things.',
      '',
      'Your father and I — things have not been good for a long time. You both know this. The will gives him everything because that is how these documents work, because that is what he will expect, because I do not have the fight left in me. But the lake house is yours. Hold onto it. Go to the birch trees. Remember what it was like before everything got complicated.',
      '',
      'I love you both. I have always loved you both.',
      '',
      'Mom',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-03-22T19:50:00-04:00',
    author: 'arthur',
    message: 'Consolidating branches. Cleaning up repository.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My personal book collection to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to my husband, Arthur Wren, to manage and maintain for the benefit of the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, in fee simple absolute.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my remains be handled at the discretion of my executor.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ]),
    postAction: 'deleteReviewAndPrivate'
  },
  {
    date: '2024-03-23T00:01:00-04:00',
    author: 'arthur',
    message: 'Removing stale branches. Unnecessary clutter.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My personal book collection to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to my husband, Arthur Wren, to manage and maintain for the benefit of the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, in fee simple absolute.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my remains be handled at the discretion of my executor.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ]),
    postAction: 'deleteContested'
  },
  {
    date: '2024-03-28T17:30:00-04:00',
    author: 'margaret',
    message: 'I found a copy of Mom\'s letter in her email drafts. She sent it to herself on February 28th. I\'m putting it here because I don\'t trust where else it might go.',
    branch: BRANCHES.contested,
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I was married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my daughter, Margaret Chen-Wren, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be placed in an irrevocable trust for the benefit of my children, Margaret Chen-Wren and David Wren, in equal shares, for their lifetimes. The property may not be sold or transferred outside the family. The trustee shall be Margaret Chen-Wren.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '## LETTER TO MY CHILDREN',
      'Margaret, David —',
      'If you are reading this, I am gone. I\'m sorry for that. I\'m sorry for a lot of things.',
      '',
      'I want you to know that this will does not contain everything I wish I could give you. Some things cannot be put in legal language. The way Margaret looked after me these last months, driving three hours each weekend, sitting through appointments no daughter should have to sit through — that is not something a bequest can honor. But I see you, sweetheart. I see everything you do.',
      '',
      'David — I know I have been distant. I know the phone calls went both ways and I was the one who stopped picking up. You deserved a mother who showed up. I was sick and I was scared and I convinced myself that you were better off without watching. I was wrong about that. I was wrong about so many things.',
      '',
      'Your father and I — things have not been good for a long time. You both know this. The will gives him everything because that is how these documents work, because that is what he will expect, because I do not have the fight left in me. But the lake house is yours. Hold onto it. Go to the birch trees. Remember what it was like before everything got complicated.',
      '',
      'I love you both. I have always loved you both.',
      '',
      'Mom',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-04-01T04:17:00-04:00',
    author: 'david',
    message: 'three weeks. margaret and arthur aren\'t talking. i keep looking at the will. i keep looking at what he changed. she wanted the birch trees and he made it "at the discretion of my executor." she wanted us to have the house and he gave himself fee simple absolute. fee simple. like she was never there.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My personal book collection to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to my husband, Arthur Wren, to manage and maintain for the benefit of the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, in fee simple absolute.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my remains be handled at the discretion of my executor.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-04-05T14:22:00-04:00',
    author: 'arthur',
    message: 'Adding notarization block for execution',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My personal book collection to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to my husband, Arthur Wren, to manage and maintain for the benefit of the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, in fee simple absolute.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my remains be handled at the discretion of my executor.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '## NOTARIZATION',
      '',
      'Sworn and subscribed before me this _____ day of ___________, 2024.',
      '',
      '_______________________',
      'Notary Public',
      'My commission expires: ___________'
    ])
  },
  {
    date: '2024-04-12T23:48:00-04:00',
    author: 'david',
    message: 'margaret found the commit history. she found all of it. every time arthur changed what mom wanted. it\'s all here. he didn\'t know we could see it.',
    branch: BRANCHES.contested,
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I was married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my daughter, Margaret Chen-Wren, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be placed in an irrevocable trust for the benefit of my children, Margaret Chen-Wren and David Wren, in equal shares, for their lifetimes. The property may not be sold or transferred outside the family. The trustee shall be Margaret Chen-Wren.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '## LETTER TO MY CHILDREN',
      'Margaret, David —',
      'If you are reading this, I am gone. I\'m sorry for that. I\'m sorry for a lot of things.',
      '',
      'I want you to know that this will does not contain everything I wish I could give you. Some things cannot be put in legal language. The way Margaret looked after me these last months, driving three hours each weekend, sitting through appointments no daughter should have to sit through — that is not something a bequest can honor. But I see you, sweetheart. I see everything you do.',
      '',
      'David — I know I have been distant. I know the phone calls went both ways and I was the one who stopped picking up. You deserved a mother who showed up. I was sick and I was scared and I convinced myself that you were better off without watching. I was wrong about that. I was wrong about so many things.',
      '',
      'Your father and I — things have not been good for a long time. You both know this. The will gives him everything because that is how these documents work, because that is what he will expect, because I do not have the fight left in me. But the lake house is yours. Hold onto it. Go to the birch trees. Remember what it was like before everything got complicated.',
      '',
      'I love you both. I have always loved you both.',
      '',
      'Mom',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-04-15T09:00:00-04:00',
    author: 'arthur',
    message: 'Contacting counsel re: repository access. Unauthorized modifications to legal documents.',
    branch: 'main',
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I am married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my sister, Helen Marsh, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My personal book collection to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to my husband, Arthur Wren, to manage and maintain for the benefit of the family.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, in fee simple absolute.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my remains be handled at the discretion of my executor.',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '## NOTARIZATION',
      '',
      'Sworn and subscribed before me this _____ day of ___________, 2024.',
      '',
      '_______________________',
      'Notary Public',
      'My commission expires: ___________'
    ])
  },
  {
    date: '2024-04-18T22:07:00-04:00',
    author: 'david',
    message: 'arthur\'s lawyer sent a letter. it says the contested branch has no legal standing. it says we should cease and desist. margaret cried. i don\'t cry. but i\'m sitting in my car outside the lake house and the birch trees are gone. he cut them down. they\'re just gone.',
    branch: BRANCHES.contested,
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I was married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my daughter, Margaret Chen-Wren, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be placed in an irrevocable trust for the benefit of my children, Margaret Chen-Wren and David Wren, in equal shares, for their lifetimes. The property may not be sold or transferred outside the family. The trustee shall be Margaret Chen-Wren.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '## LETTER TO MY CHILDREN',
      'Margaret, David —',
      'If you are reading this, I am gone. I\'m sorry for that. I\'m sorry for a lot of things.',
      '',
      'I want you to know that this will does not contain everything I wish I could give you. Some things cannot be put in legal language. The way Margaret looked after me these last months, driving three hours each weekend, sitting through appointments no daughter should have to sit through — that is not something a bequest can honor. But I see you, sweetheart. I see everything you do.',
      '',
      'David — I know I have been distant. I know the phone calls went both ways and I was the one who stopped picking up. You deserved a mother who showed up. I was sick and I was scared and I convinced myself that you were better off without watching. I was wrong about that. I was wrong about so many things.',
      '',
      'Your father and I — things have not been good for a long time. You both know this. The will gives him everything because that is how these documents work, because that is what he will expect, because I do not have the fight left in me. But the lake house is yours. Hold onto it. Go to the birch trees. Remember what it was like before everything got complicated.',
      '',
      'I love you both. I have always loved you both.',
      '',
      'Mom',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  },
  {
    date: '2024-04-25T15:45:00-04:00',
    author: 'margaret',
    message: 'We\'re meeting with a lawyer next week. David found the commit where Arthur redirected the lake house. February 11th, 6:03 AM. The metadata doesn\'t lie.',
    branch: BRANCHES.contested,
    content: makeWillDoc([
      '# LAST WILL AND TESTAMENT OF ELEANOR WREN',
      '',
      'I, Eleanor Wren, a resident of Hartford County, Connecticut, being of sound and disposing mind and memory, do hereby make, publish, and declare this to be my Last Will and Testament, hereby revoking all prior wills and codicils made by me.',
      '',
      '## ARTICLE I: DECLARATION',
      'I declare that I was married to Arthur Wren. I have two living children: Margaret Chen-Wren (age 34) and David Wren (age 31). I have no other living children, nor any deceased children leaving issue.',
      '',
      '## ARTICLE II: EXECUTOR',
      'I appoint my husband, Arthur Wren, to serve as executor of this will without bond. In the event he is unable or unwilling to serve, I appoint my daughter, Margaret Chen-Wren, as successor executor, also without bond.',
      '',
      '## ARTICLE III: SPECIFIC BEQUESTS',
      'I bequeath the following specific items:',
      '- My grandmother\'s wedding ring to my daughter, Margaret Chen-Wren.',
      '- My collection of first editions (approximately 340 volumes) to my son, David Wren.',
      '- The property known as 44 Cedar Pond Road, referred to as "the lake house," to be placed in an irrevocable trust for the benefit of my children, Margaret Chen-Wren and David Wren, in equal shares, for their lifetimes. The property may not be sold or transferred outside the family. The trustee shall be Margaret Chen-Wren.',
      '',
      '## ARTICLE IV: RESIDUARY ESTATE',
      'All the rest, residue, and remainder of my estate, of whatever kind and wherever situated, I give, devise, and bequeath to my husband, Arthur Wren, if he survives me by thirty (30) days. If my husband does not survive me, my residuary estate shall be divided equally between my children, per stirpes.',
      '',
      '## ARTICLE V: GUARDIANSHIP PROVISIONS',
      'No guardian provisions required. All beneficiaries are legal adults.',
      '',
      '## ARTICLE VI: FINAL WISHES',
      'I direct that my body be cremated. I request that my ashes be scattered at Cedar Pond, among the birch trees on the eastern shore, in the morning light.',
      '',
      '## LETTER TO MY CHILDREN',
      'Margaret, David —',
      'If you are reading this, I am gone. I\'m sorry for that. I\'m sorry for a lot of things.',
      '',
      'I want you to know that this will does not contain everything I wish I could give you. Some things cannot be put in legal language. The way Margaret looked after me these last months, driving three hours each weekend, sitting through appointments no daughter should have to sit through — that is not something a bequest can honor. But I see you, sweetheart. I see everything you do.',
      '',
      'David — I know I have been distant. I know the phone calls went both ways and I was the one who stopped picking up. You deserved a mother who showed up. I was sick and I was scared and I convinced myself that you were better off without watching. I was wrong about that. I was wrong about so many things.',
      '',
      'Your father and I — things have not been good for a long time. You both know this. The will gives him everything because that is how these documents work, because that is what he will expect, because I do not have the fight left in me. But the lake house is yours. Hold onto it. Go to the birch trees. Remember what it was like before everything got complicated.',
      '',
      'I love you both. I have always loved you both.',
      '',
      'Mom',
      '',
      '_______________________',
      'Eleanor Wren',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________',
      '',
      '_______________________',
      'Witness',
      'Date: ___________'
    ])
  }
];

function seedRepo(force = false) {
  const repoPath = repo.createRepo(force);

  for (const commit of COMMIT_TIMELINE) {
    const author = AUTHORS[commit.author];

    repo.createCommit({
      authorName: author.name,
      authorEmail: author.email,
      date: commit.date,
      message: commit.message,
      content: commit.content,
      filePath: 'document.md',
      branch: commit.branch,
      tag: commit.tag || null
    });

    if (commit.postAction === 'deleteReviewAndPrivate') {
      try { repo.deleteBranch(BRANCHES.review); } catch (_) { /* branch may not exist here */ }
      try { repo.deleteBranch(BRANCHES.private); } catch (_) { /* branch may not exist here */ }
    }
    if (commit.postAction === 'deleteContested') {
      try { repo.deleteBranch(BRANCHES.contested); } catch (_) { /* branch may not exist here */ }
    }
  }

  try {
    repo.checkoutBranch('main');
  } catch (_) {
    /* already on main */
  }

  return {
    path: repoPath,
    commitCount: COMMIT_TIMELINE.length,
    authors: Object.values(AUTHORS).map(a => a.name)
  };
}

function getTimeline() {
  return COMMIT_TIMELINE.map((commit, index) => ({
    index,
    date: commit.date,
    author: AUTHORS[commit.author].name,
    authorKey: commit.author,
    message: commit.message,
    branch: commit.branch,
    tag: commit.tag || null
  }));
}

function getAuthors() {
  return AUTHORS;
}

function getBranchNames() {
  return BRANCHES;
}

module.exports = {
  seedRepo,
  getAuthors,
  getBranchNames,
  getTimeline
};
